In [1]:
import numpy as np

In [2]:
a = [2, 5, 7]

In [3]:
b = [3, 12, 27]

In [4]:
a+b

[2, 5, 7, 3, 12, 27]

In [5]:
c = [m+n for m, n in zip(a,b)]

In [6]:
c

[5, 17, 34]

In [7]:
sum(a)

14

In [8]:
np_a = np.array(a)

In [10]:
np_b = np.array(b)

In [11]:
np_a + np_b

array([ 5, 17, 34])

In [12]:
p = np.array([1,2,"abc"])

In [13]:
p

array(['1', '2', 'abc'], dtype='<U11')

In [14]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [15]:
np_a.max()

7

In [16]:
np_a.mean()

4.666666666666667

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np_a*np.ones(3)

array([2., 5., 7.])

In [20]:
np_a*[3]

array([ 6, 15, 21])

In [21]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [22]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [23]:
np_a[1]

5

In [24]:
np_a[1:]

array([5, 7])

In [25]:
np_a[0:2]

array([2, 5])

In [27]:
np_2d = np.array([[1,2],[3,4]])

In [28]:
np_2d.sum()

10

In [29]:
np_2d.sum(axis=0)

array([4, 6])

In [30]:
np_2d.sum(axis=1)

array([3, 7])

In [31]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [32]:
np_2d.T

array([[1, 3],
       [2, 4]])

In [34]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [36]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
np_2d

array([[1, 2],
       [3, 4]])

In [38]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [39]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [41]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [43]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [44]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [45]:
np_dotp[0,1]

210

In [46]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [47]:
np_dotp[0:2,0]

array([2001, 4003])

In [48]:
np_rs = np.array([1,2,3,4,5,6])

In [49]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [50]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [54]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [57]:
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.random(2)

TypeError: 'module' object is not callable

In [59]:
np.random.random(2)

array([0.43365602, 0.67705795])

In [60]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [61]:
import numpy.random as random

In [62]:
random(2)

TypeError: 'module' object is not callable

In [63]:
random.random(2)

array([0.26399133, 0.7125254 ])

In [65]:
random.random([3,2])

array([[0.30526688, 0.41513002],
       [0.598052  , 0.11485611],
       [0.0684223 , 0.54712717]])

In [66]:
import numpy.linalg as la

In [67]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
la.eig(np_2d)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [70]:
la.svd(np_2d)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [71]:
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [75]:
random.rand(2,3)*5

array([[1.91814336, 3.3888604 , 1.73449056],
       [4.35126763, 2.85394498, 4.83614907]])

In [74]:
random.randn(2,3)

array([[-1.23473641,  1.20362352, -0.0691662 ],
       [ 0.0334294 ,  1.00109125, -0.22592634]])

In [76]:
random.randint(-2,3,5)

array([ 1, -1, -2,  2,  0])

In [77]:
random.shuffle(np_rs)

In [78]:
np_rs

array([3, 6, 4, 1, 2, 5])

In [79]:
random.choice(np_rs, 2)

array([1, 6])

In [80]:
random.binomial(20,0.3)

5

In [81]:
random.binomial(20, 0.3, 7)

array([ 5,  8,  2,  7,  7, 10,  4])

In [82]:
random.exponential(0.7,4)

array([0.13372559, 0.62232793, 1.1424338 , 0.36568844])

In [ ]:
%%time


In [83]:
random.normal(-5,12,3)

array([-13.16651465,  -0.12575013,  -1.52670445])

In [84]:
random.logistic(-2,4,7)

array([-13.86959627,  -6.28421112,  -2.89562533,  -2.56350521,
         3.03949534,  -9.1472225 ,   6.53402689])

In [85]:
np_2d.shape

(2, 2)

In [86]:
np_2d.dtype

dtype('int32')

In [87]:
type(np_2d)

numpy.ndarray

In [90]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [94]:
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [95]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [96]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [97]:
np_x = np.array(x)
np_y = np.array(y)

In [100]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


Wall time: 1.96 s


In [99]:
%%time
np_z = np_x+np_y

Wall time: 32.9 ms
