In [6]:
import numpy as np

In [7]:
a = [2, 5, 7]

In [8]:
b = [3, 12, 27]

In [9]:
a+b

[2, 5, 7, 3, 12, 27]

In [10]:
c = [m+n for m, n in zip(a,b)]

In [11]:
c

[5, 17, 34]

In [12]:
sum(a)

14

In [13]:
np_a = np.array(a)

In [14]:
np_b = np.array(b)

In [15]:
np_a + np_b

array([ 5, 17, 34])

In [16]:
p = np.array([1,2,"abc"])

In [17]:
p

array(['1', '2', 'abc'], dtype='<U11')

In [18]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [ ]:
np_a.max()

In [19]:
np_a.mean()

4.666666666666667

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np_a*np.ones(3)

array([2., 5., 7.])

In [23]:
np_a*[3]

array([ 6, 15, 21])

In [24]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [25]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [26]:
np_a[1]

5

In [27]:
np_a[1:]

array([5, 7])

In [28]:
np_a[0:2]

array([2, 5])

In [29]:
np_2d = np.array([[1,2],[3,4]])

In [30]:
np_2d.sum()

10

In [31]:
np_2d.sum(axis=0)

array([4, 6])

In [32]:
np_2d.sum(axis=1)

array([3, 7])

In [33]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [34]:
np_2d.T

array([[1, 3],
       [2, 4]])

In [35]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [36]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
np_2d

array([[1, 2],
       [3, 4]])

In [38]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [39]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [40]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [41]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [42]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [43]:
np_dotp[0,1]

210

In [44]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [45]:
np_dotp[0:2,0]

array([2001, 4003])

In [46]:
np_rs = np.array([1,2,3,4,5,6])

In [47]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [48]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [52]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [54]:
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.random(2)

TypeError: 'module' object is not callable

In [56]:
np.random.random(2)

array([0.61939634, 0.69540099])

In [57]:
import np.random as random

ModuleNotFoundError: No module named 'np'

In [58]:
import numpy.random as random

In [59]:
random(2)

TypeError: 'module' object is not callable

In [60]:
random.random(2)

array([0.24991335, 0.52922267])

In [61]:
random.random([3,2])

array([[0.30373153, 0.93695255],
       [0.65425126, 0.01571063],
       [0.84501543, 0.45653796]])

In [62]:
import numpy.linalg as la

In [63]:
la.inv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
la.eig(np_2d)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [65]:
la.svd(np_2d)

SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))

In [66]:
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
random.rand(2,3)*5

array([[2.21756304, 2.28333019, 3.10768155],
       [3.85151334, 0.62341675, 1.63254487]])

In [68]:
random.randn(2,3)

array([[-0.44852725,  1.40975698,  0.68921665],
       [ 0.85285963,  0.85186061, -0.03800664]])

In [69]:
random.randint(-2,3,5)

array([-1,  1,  1, -2,  0])

In [70]:
random.shuffle(np_rs)

In [71]:
np_rs

array([3, 2, 4, 1, 6, 5])

In [72]:
random.choice(np_rs, 2)

array([4, 5])

In [73]:
random.binomial(20,0.3)

6

In [74]:
random.binomial(20, 0.3, 7)

array([8, 2, 7, 6, 6, 6, 4])

In [75]:
random.exponential(0.7,4)

array([0.63040658, 0.05184521, 0.2629849 , 0.68567761])

In [76]:
%%time


UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [77]:
random.normal(-5,12,3)

array([-14.08195994,  -0.74385874,  -7.72795671])

In [78]:
random.logistic(-2,4,7)

array([ 8.49424683, 13.55197041,  1.81429774,  2.32158888, 16.07838025,
        0.69180049, -3.95099991])

In [79]:
np_2d.shape

(2, 2)

In [80]:
np_2d.dtype

dtype('int32')

In [81]:
type(np_2d)

numpy.ndarray

In [82]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [83]:
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [84]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [85]:
N=10000000
x=list(range(N))
y=list(range(N))
z=[]

In [86]:
np_x = np.array(x)
np_y = np.array(y)

In [87]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


CPU times: total: 4.72 s
Wall time: 10.8 s


In [88]:
%%time
np_z = np_x+np_y

CPU times: total: 297 ms
Wall time: 505 ms


In [89]:
import pandas as pd
import numpy as np

In [90]:
data = pd.read_csv('NumpyExerciseData.csv')

**Newton Method**

In [91]:
data.head()

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0   1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1   1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2   1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3   1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4   1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   

   Unnamed: 10  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [92]:
X = data.loc[1:40, ['X0', 'X1', 'X2', 'X3', 'X4', 'X5']].values
y = data.loc[1:40, 'y'].values

In [93]:
X_transpose = X.T

In [94]:
X_transpose_X = np.dot(X_transpose, X)

In [95]:
X_transpose_X_inv = np.linalg.inv(X_transpose_X)

In [96]:
X_transpose_y = np.dot(X_transpose, y)

In [97]:
result = np.dot(X_transpose_X_inv, X_transpose_y)


In [98]:
print(result)

[-7.83196374  3.26458338  0.16631204 12.19246692  0.38231333 -1.58835343]


**QUESTION-2**

***SSR, MSR and RMSE***

In [99]:
X_train = data.loc[1:40, ['X0', 'X1', 'X2', 'X3', 'X4', 'X5']].values
y_train = data.loc[1:40, 'y'].values
X_test = data.loc[42:50, ['X0', 'X1', 'X2', 'X3', 'X4', 'X5']].values
y_test = data.loc[42:50, 'y'].values

In [100]:
X_transpose = X_train.T
X_transpose_X = np.dot(X_transpose, X_train)
X_transpose_X_inv = np.linalg.inv(X_transpose_X)
X_transpose_y = np.dot(X_transpose, y_train)
w = np.dot(X_transpose_X_inv, X_transpose_y)

In [101]:
y_train_pred = np.dot(X_train, w)
y_test_pred = np.dot(X_test, w)

In [102]:
#calculating the train of SSR,MSR and RMSE
SSR_train = np.sum((y_train - y_train_pred) ** 2)
MSR_train = SSR_train / len(y_train)
RMSE_train = np.sqrt(MSR_train)

In [103]:
#calculating the test of SSR,MSR and RMSE
SSR_test = np.sum((y_test - y_test_pred) ** 2)
MSR_test = SSR_test / len(y_test)
RMSE_test = np.sqrt(MSR_test)

In [104]:
#printing the train of SSR, MSR AND RMSE
print("Train Error Metrics:")
print(f"SSR: {SSR_train}")
print(f"MSR: {MSR_train}")
print(f"RMSE: {RMSE_train}")

Train Error Metrics:
SSR: 2.905634003203798
MSR: 0.07264085008009495
RMSE: 0.2695196654793393


In [105]:
#printing the test of SSR, MSR AND RMSE
print("\nTest Error Metrics:")
print(f"SSR: {SSR_test}")
print(f"MSR: {MSR_test}")
print(f"RMSE: {RMSE_test}")


Test Error Metrics:
SSR: 0.8699465589724562
MSR: 0.10874331987155703
RMSE: 0.32976252041667353


**Regularized Newton**

In [106]:
X_train = data.loc[1:40, ['X0', 'X1', 'X2', 'X3', 'X4', 'X5']].values
y_train = data.loc[1:40, 'y'].values

In [107]:
lambda_reg = 1

In [108]:
#transpose
X_transpose = X_train.T
X_transpose_X = np.dot(X_transpose, X_train)
I = np.eye(X_transpose_X.shape[0])
X_transpose_X_reg = X_transpose_X + lambda_reg * I
X_transpose_X_reg_inv = np.linalg.inv(X_transpose_X_reg)
X_transpose_y = np.dot(X_transpose, y_train)
w_reg = np.dot(X_transpose_X_reg_inv, X_transpose_y)

In [109]:
#printing the reg_weights
print("Regularized Weights (w):")
print(w_reg)

Regularized Weights (w):
[-3.82677947  3.14344878  0.1119756   9.8579322   0.36969429 -1.50614557]


**Use lambda as 0.17**

In [110]:
lambda_reg = 0.17

In [111]:
#transpose
X_transpose = X_train.T
X_transpose_X = np.dot(X_transpose, X_train)
I = np.eye(X_transpose_X.shape[0])  # Identity matrix of the same size as X'X
X_transpose_X_reg = X_transpose_X + lambda_reg * I
X_transpose_X_reg_inv = np.linalg.inv(X_transpose_X_reg)
X_transpose_y = np.dot(X_transpose, y_train)
w_reg = np.dot(X_transpose_X_reg_inv, X_transpose_y)

In [112]:
#printing the reg_weights
print("Regularized Weights (w):")
print(w_reg)

Regularized Weights (w):
[-6.7562687   3.2347398   0.15118389 11.67719211  0.37881104 -1.56678791]


**R2values for both Newton and Regularized Newton methods**

In [113]:
#  Extracting rows 2 to 41 for training data
X_train = data.loc[1:40, ['X0', 'X1', 'X2', 'X3', 'X4', 'X5']].values
y_train = data.loc[1:40, 'y'].values

#  Extracting rows 43 to 51 for test data
X_test = data.loc[42:50, ['X0', 'X1', 'X2', 'X3', 'X4', 'X5']].values
y_test = data.loc[42:50, 'y'].values

In [114]:
#regularized computation ((X'X + lambda*I)^-1)*X'y
lambda_reg = 0.17

In [115]:
# Training
X_transpose = X_train.T
X_transpose_X = np.dot(X_transpose, X_train)
X_transpose_X_inv = np.linalg.inv(X_transpose_X)
X_transpose_y = np.dot(X_transpose, y_train)
w_newton = np.dot(X_transpose_X_inv, X_transpose_y)

In [116]:
# Training
I = np.eye(X_transpose_X.shape[0])
X_transpose_X_reg = X_transpose_X + lambda_reg * I
X_transpose_X_reg_inv = np.linalg.inv(X_transpose_X_reg)
w_reg = np.dot(X_transpose_X_reg_inv, X_transpose_y)

In [117]:
# Generate y values for both training and test data
y_train_pred_newton = np.dot(X_train, w_newton)
y_test_pred_newton = np.dot(X_test, w_newton)
y_train_pred_reg = np.dot(X_train, w_reg)
y_test_pred_reg = np.dot(X_test, w_reg)

In [118]:
#R-squared for training data with newton method
SSR_train_newton = np.sum((y_train - y_train_pred_newton) ** 2)
SST_train = np.sum((y_train - np.mean(y_train)) ** 2)
R2_train_newton = 1 - (SSR_train_newton / SST_train)

In [119]:
#R-squared for test data with newton method
SSR_test_newton = np.sum((y_test - y_test_pred_newton) ** 2)
SST_test = np.sum((y_test - np.mean(y_test)) ** 2)
R2_test_newton = 1 - (SSR_test_newton / SST_test)

In [120]:
#R-squared for training data with Regularized Newton
SSR_train_reg = np.sum((y_train - y_train_pred_reg) ** 2)
R2_train_reg = 1 - (SSR_train_reg / SST_train)

In [121]:
#R-squared for test data Regularized Newton
SSR_test_reg = np.sum((y_test - y_test_pred_reg) ** 2)
R2_test_reg = 1 - (SSR_test_reg / SST_test)

In [122]:
# Printing
print("R-squared values:")
print(f"Training R2 (Newton): {R2_train_newton}")
print(f"Test R2 (Newton): {R2_test_newton}")
print(f"Training R2 (Regularized Newton): {R2_train_reg}")
print(f"Test R2 (Regularized Newton): {R2_test_reg}")


R-squared values:
Training R2 (Newton): 0.9992912223434068
Test R2 (Newton): 0.99920398347572
Training R2 (Regularized Newton): 0.9987347740766597
Test R2 (Regularized Newton): 0.999221615499757


In [124]:
data.head()

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0   1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1   1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2   1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3   1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4   1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   

   Unnamed: 10  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [125]:
#droping the NaN column
data = data.dropna(axis=1)
data.head()

X0     X1     X2  X3  X4   X5   y
0   1  5.768  62.55   0  28  2.6  28
1   1  8.949  66.91   0  27 -2.0  46
2   1  1.024  34.42   0  20 -3.4  14
3   1  4.534  47.93   0  10  1.1  17
4   1  8.641  35.26   0  30  3.8  32

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score
data = pd.read_csv('NumpyExerciseData.csv')
data = data.dropna(axis=1) #droping the NaN value column

def extract_features_targets(data, start_row, end_row):
    subset_data = data.iloc[start_row:end_row]
    X = subset_data.iloc[:, :-1].values
    y = subset_data.iloc[:, -1].values
    return X, y

def ridge_regression(X_train, y_train, X_test, y_test, alpha):
    model = Ridge(alpha=alpha)
    model.fit(X_train, y_train)

    #train and test
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)


    msr_train = mean_squared_error(y_train, y_train_pred)
    msr_test = mean_squared_error(y_test, y_test_pred)
    r2_train = r2_score(y_train, y_train_pred)
    r2_test = r2_score(y_test, y_test_pred)

    return msr_train, msr_test, r2_train, r2_test

#printing
def print_results(description, msr_train, msr_test, r2_train, r2_test):
    print(f"{description}:")
    print(f"MSR on Train: {msr_train}")
    print(f"MSR on Test: {msr_test}")
    print(f"R-squared on Train: {r2_train}")
    print(f"R-squared on Test: {r2_test}")
    print()

#For Split 1
X_train_1, y_train_1 = extract_features_targets(data, 1, 41)
X_test_1, y_test_1 = extract_features_targets(data, 41, 51)
msr_train_1, msr_test_1, r2_train_1, r2_test_1 = ridge_regression(X_train_1, y_train_1, X_test_1, y_test_1, 0.83)
print_results("Split 1", msr_train_1, msr_test_1, r2_train_1, r2_test_1)

#For Split 2
X_train_2, y_train_2 = extract_features_targets(data, 1, 26)
X_test_2, y_test_2 = extract_features_targets(data, 26, 51)
msr_train_2, msr_test_2, r2_train_2, r2_test_2 = ridge_regression(X_train_2, y_train_2, X_test_2, y_test_2, 0.17)
print_results("Split 2", msr_train_2, msr_test_2, r2_train_2, r2_test_2)

#For Split 3
msr_train_3, msr_test_3, r2_train_3, r2_test_3 = ridge_regression(X_train_2, y_train_2, X_test_2, y_test_2, 0.83)
print_results("Split 3", msr_train_3, msr_test_3, r2_train_3, r2_test_3)

#For Split 4
X_train_4, y_train_4 = extract_features_targets(data, 1, 11)
X_test_4, y_test_4 = extract_features_targets(data, 11, 51)
msr_train_4, msr_test_4, r2_train_4, r2_test_4 = ridge_regression(X_train_4, y_train_4, X_test_4, y_test_4, 0.17)
print_results("Split 4", msr_train_4, msr_test_4, r2_train_4, r2_test_4)

#For Split 5
msr_train_5, msr_test_5, r2_train_5, r2_test_5 = ridge_regression(X_train_4, y_train_4, X_test_4, y_test_4, 0.83)
print_results("Split 5", msr_train_5, msr_test_5, r2_train_5, r2_test_5)
